#!/bin/bash
ROOT_DIR=$(dirname $(realpath $0))
export network_number=$(cat $ROOT_DIR/vars/network_number)
export gateway=$(cat $ROOT_DIR/vars/gateway)
export node=$(cat $ROOT_DIR/vars/node)
export stat=$(cat $ROOT_DIR/vars/stat)
export git=$(cat $ROOT_DIR/vars/git)
export chain=$(cat $ROOT_DIR/vars/chain)
export fisherman=$(cat $ROOT_DIR/vars/fisherman)
export staking=$(cat $ROOT_DIR/vars/staking)
export portal=$(cat $ROOT_DIR/vars/portal)
export web=$(cat $ROOT_DIR/vars/web)
export api=$(cat $ROOT_DIR/vars/api)
export gwman=$(cat $ROOT_DIR/vars/gwman)
export session=$(cat $ROOT_DIR/vars/session)
